In [5]:
import pandas as pd
import numpy as np 
df=pd.read_csv('https://raw.githubusercontent.com/shsarv/Machine-Learning-Projects/main/Diabetes%20Prediction%20%5BEND%202%20END%5D/dataset/kaggle_diabetes.csv')

In [6]:
df


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [7]:
df['Glucose	'].value_counts()

KeyError: 'Glucose\t'

In [59]:
df['BloodPressure'].value_counts()

BloodPressure
74     145
70     144
78     128
68     125
64     120
72     118
80      98
62      94
76      93
60      92
0       90
82      83
88      67
66      65
84      61
90      55
58      54
86      53
50      31
54      31
56      31
52      29
75      20
65      19
94      18
85      14
48      13
92      12
44      11
106      9
100      9
96       8
98       8
110      7
46       6
104      5
108      5
55       4
61       4
30       3
122      3
102      3
114      3
38       3
95       2
24       2
40       2
Name: count, dtype: int64

In [37]:
df['Outcome'].value_counts()

Outcome
0    1316
1     684
Name: count, dtype: int64

In [9]:
x=df.drop('Outcome',axis=1)
y=df['Outcome']

In [10]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [11]:
lgr.fit(x_test,y_test)

c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
lgr.score(x_test,y_test)

0.806

In [13]:
lgr.score(x_train,y_train)

0.776

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(lgr,x_train,y_train,cv=10)

c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

array([0.76666667, 0.76      , 0.82      , 0.75333333, 0.77333333,
       0.81333333, 0.72666667, 0.79333333, 0.73333333, 0.71333333])

In [16]:
cross_val_score(lgr,x_test,y_test,cv=10)

c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

array([0.74, 0.74, 0.84, 0.82, 0.74, 0.82, 0.74, 0.76, 0.8 , 0.8 ])

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

print(confusion_matrix(y_test,lgr.predict(x_test)))
print(accuracy_score(y_test,lgr.predict(x_test)))
print(precision_score(y_test,lgr.predict(x_test)))
print(recall_score(y_test,lgr.predict(x_test)))
print(f1_score(y_test,lgr.predict(x_test)))

[[287  33]
 [ 64 116]]
0.806
0.7785234899328859
0.6444444444444445
0.7051671732522796


In [56]:
import pickle 
with open('model.pickle','wb')as model_file:
    pickle.dump(lgr,model_file)